spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatalivedb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 1911
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: chat.alive.adm@gmail.com
    password: kyci xqmk unlu hvbn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    time-zone: America/Sao_Paulo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc.time_zone: America/Sao_Paulo
server:
  port: 8080

jwt:
  secret: uz4i5uO5A4+1Ic0o1l3C43PfKc3RQxT+J4rLTyAxvYk=

